const engWordList = [
    { word: "book", hint: "Something you read that has pages.", difficulty: 1 },
    { word: "school", hint: "A place where you learn.", difficulty: 1 },
    { word: "computer", hint: "A machine for searching information on the internet.", difficulty: 1 },
    { word: "teacher", hint: "Someone who teaches.", difficulty: 1 },
    { word: "student", hint: "Someone who learns.", difficulty: 1 },
    { word: "pencil", hint: "A tool for writing or drawing.", difficulty: 1 },
    { word: "science", hint: "Studying about things work.", difficulty: 1 },
    { word: "math", hint: "Working with numbers and shapes.", difficulty: 1 },
    { word: "history", hint: "Learning about the past.", difficulty: 1 },
    { word: "music", hint: "What people play in a nice sound way.", difficulty: 1 },
    { word: "alphabet", hint: "Letters that make words.", difficulty: 1 },
    { word: "grammar", hint: "Rules for speaking and writing.", difficulty: 1 },
    { word: "dictionary", hint: "A book with a lot of words with definitions.", difficulty: 1 },
    { word: "poetry", hint: "What people cite in a fancy way.", difficulty: 1 },
    { word: "essay", hint: "A short piece of writing.", difficulty: 1 },
    { word: "art", hint: "Making pretty things.", difficulty: 1 },
    { word: "exam", hint: "A big test.", difficulty: 1 },

    { word: "language", hint: "How people talk to each other.", difficulty: 2 },
    { word: "novel", hint: "A fictional long story.", difficulty: 2 },
    { word: "university", hint: "A school for grown-ups.", difficulty: 2 },
    { word: "internet", hint: "Worldwide computer network.", difficulty: 2 },
    { word: "lecture", hint: "A study lesson to teach people.", difficulty: 2 },
    { word: "experiment", hint: "Experimenting things to learn.", difficulty: 2 },
    { word: "equation", hint: "A math sentence.", difficulty: 2 },
    { word: "biography", hint: "Life story by someone else.", difficulty: 2 },
    { word: "synonym", hint: "Same meaning of word.", difficulty: 2 },
    { word: "continent", hint: "Big land area.", difficulty: 2 },
    { word: "communication", hint: "Sharing information.", difficulty: 2 },
    { word: "landscape", hint: "View of land.", difficulty: 2 },
    { word: "photography", hint: "Taking and editing pictures.", difficulty: 2 },

    { word: "algorithm", hint: "A set of rules for solving problems, often used by computers.", difficulty: 3 },
    { word: "chemistry", hint: "Science studying chemicals.", difficulty: 3 },
    { word: "crypto", hint: "Digital money.", difficulty: 3 },
    { word: "neuroscience", hint: "Study of brains and nerves.", difficulty: 3 },
    { word: "psychology", hint: "Learning about how brains work.", difficulty: 3 },
    { word: "sociology", hint: "Studying how people live together.", difficulty: 3 },
    { word: "philosophy", hint: "Thinking deeply about life.", difficulty: 3 },
    { word: "architecture", hint: "Designing and building things.", difficulty: 3 },
    { word: "engineering", hint: "Making things with science.", difficulty: 3 },
    { word: "astronomy", hint: "Looking at space and stars.", difficulty: 3 },
    { word: "meteorology", hint: "Studying weather.", difficulty: 3 },
    { word: "geology", hint: "Learning about rocks and Earth.", difficulty: 3 },
    { word: "paleontology", hint: "Finding and studying old living things.", difficulty: 3 },
    { word: "linguistics", hint: "Learning about languages.", difficulty: 3 },
    { word: "archaeology", hint: "Digging up and learning about old stuff.", difficulty: 3 },
];

const mathWordList = [
    { word: "addition", hint: "Combining numbers to find the total.", difficulty: 1 },
    { word: "subtraction", hint: "Taking away one number from another.", difficulty: 1 },
    { word: "multiplication", hint: "Repeated addition or grouping.", difficulty: 1 },
    { word: "division", hint: "Sharing or grouping into equal parts.", difficulty: 1 },
    { word: "number", hint: "Used for counting or measuring.", difficulty: 1 },
    { word: "decimal", hint: "Numbers with a decimal point.", difficulty: 1 },
    { word: "integer", hint: "Whole numbers, positive or negative.", difficulty: 1 },
    { word: "triangle", hint: "A shape with three sides.", difficulty: 1 },
    { word: "circle", hint: "Shape with no sides.", difficulty: 1 },
    { word: "equation", hint: "Mathematical statement with equal sign.", difficulty: 1 },
    { word: "even", hint: "Number divisible by 2.", difficulty: 1 },
    { word: "odd", hint: "Number not divisible by 2.", difficulty: 1 },

    { word: "geometry", hint: "Study of shapes and space.", difficulty: 2 },
    { word: "series", hint: "Sum of a sequence.", difficulty: 2 },
    { word: "slope", hint: "Steepness of a line.", difficulty: 2 },
    { word: "average", hint: "Typical number in a group.", difficulty: 2 },
    { word: "rectangle", hint: "Four-sided shape with 90-degree angles.", difficulty: 2 },
    { word: "square", hint: "Rectangle with all sides equal.", difficulty: 2 },
    { word: "cube", hint: "Three-dimensional square.", difficulty: 2 },
    { word: "parallel", hint: "Lines that never meet.", difficulty: 2 },
    { word: "congruent", hint: "Same size and shape.", difficulty: 2 },
    { word: "similar", hint: "Same shape but different size.", difficulty: 2 },
    { word: "matrix", hint: "Grid of numbers or symbols.", difficulty: 2 },
    { word: "calculus", hint: "Studying change and motion.", difficulty: 2 },

    { word: "mode", hint: "Most common number.", difficulty: 3 },
    { word: "median", hint: "Middle number when numbers are in order.", difficulty: 3 },
    { word: "prime", hint: "Number divisible only by 1 and itself.", difficulty: 3 },
    { word: "algebra", hint: "Using letters to represent numbers.", difficulty: 3 },
    { word: "trigonometry", hint: "Triangle and angle math.", difficulty: 3 },
    { word: "probability", hint: "Chance of something happening.", difficulty: 3 },
    { word: "statistics", hint: "Collecting and analyzing data.", difficulty: 3 },
    { word: "exponent", hint: "Number showing repeated multiplication.", difficulty: 3 },
    { word: "radical", hint: "Square root or cube root.", difficulty: 3 },
    { word: "derivative", hint: "Rate of change.", difficulty: 3 },
    { word: "integral", hint: "Finding area under a curve.", difficulty: 3 },
    { word: "limit", hint: "Approaching a value.", difficulty: 3 },
    { word: "sequence", hint: "Ordered list of numbers.", difficulty: 3 },
    { word: "intercept", hint: "Where a line crosses an axis.", difficulty: 3 },
    { word: "vector", hint: "Arrow representing direction and magnitude.", difficulty: 3 },
];

const scienceWordList = [
    { word: "atom", hint: "Smallest part of matter.", difficulty: 1 },
    { word: "cell", hint: "Smallest part of life.", difficulty: 1 },
    { word: "gravity", hint: "Pulls things down.", difficulty: 1 },
    { word: "energy", hint: "Makes things work.", difficulty: 1 },
    { word: "force", hint: "Push or pull.", difficulty: 1 },
    { word: "molecule", hint: "Group of atoms.", difficulty: 1 },
    { word: "temperature", hint: "How hot or cold.", difficulty: 1 },
    { word: "evaporation", hint: "Liquid to gas.", difficulty: 1 },
    { word: "condensation", hint: "Gas to liquid.", difficulty: 1 },
    { word: "photosynthesis", hint: "Plants making food from sunlight.", difficulty: 1 },
    { word: "digestion", hint: "Breaking down food.", difficulty: 1 },
    { word: "respiration", hint: "Breathing.", difficulty: 1 },
    { word: "reflection", hint: "Light bouncing back.", difficulty: 1 },
    { word: "magnetism", hint: "Attraction of magnets.", difficulty: 1 },
    { word: "electricity", hint: "Flow of electric charge.", difficulty: 1 },
    { word: "voltage", hint: "Electric force.", difficulty: 1 },
    { word: "current", hint: "Electric flow.", difficulty: 1 },
    { word: "lunar", hint: "About the moon.", difficulty: 1 },
    { word: "solar", hint: "About the sun.", difficulty: 1 },

    { word: "photosynthesis", hint: "Plants make food from sunlight.", difficulty: 2 },
    { word: "metabolism", hint: "How your body uses energy.", difficulty: 2 },
    { word: "ecosystem", hint: "Community of living things and their environment.", difficulty: 2 },
    { word: "biodiversity", hint: "Variety of life in an area.", difficulty: 2 },
    { word: "evaporation", hint: "Liquid to gas process.", difficulty: 2 },
    { word: "condensation", hint: "Gas to liquid process.", difficulty: 2 },
    { word: "circulation", hint: "Movement of blood in the body.", difficulty: 2 },
    { word: "respiration", hint: "Breathing process.", difficulty: 2 },
    { word: "diffusion", hint: "Movement of particles from high to low concentration.", difficulty: 2 },
    { word: "genetics", hint: "Study of heredity and genes.", difficulty: 2 },
    { word: "evolution", hint: "How species change over time.", difficulty: 2 },
    { word: "gravity", hint: "Force pulling objects toward Earth.", difficulty: 2 },
    { word: "friction", hint: "Force that opposes motion.", difficulty: 2 },
    { word: "magnetism", hint: "Force of attraction or repulsion by magnets.", difficulty: 2 },
    { word: "electricity", hint: "Flow of electric charge.", difficulty: 2 },

    { word: "homeostasis", hint: "Maintaining internal balance in an organism.", difficulty: 3 },
    { word: "photosynthesis", hint: "Process plants use to make food from sunlight.", difficulty: 3 },
    { word: "metamorphosis", hint: "Transformation from larva to adult in insects.", difficulty: 3 },
    { word: "chromosome", hint: "Structure containing genetic information.", difficulty: 3 },
    { word: "nucleus", hint: "Control center of a cell.", difficulty: 3 },
    { word: "osmosis", hint: "Water moves through a semipermeable membrane.", difficulty: 3 },
    { word: "mitochondria", hint: "Powerhouse of the cell, produces energy.", difficulty: 3 },
    { word: "ecosystem", hint: "Community of living organisms and their environment.", difficulty: 3 },
    { word: "biodiversity", hint: "Variety of species in an ecosystem.", difficulty: 3 },
    { word: "evolution", hint: "Change in species over time.", difficulty: 3 },
    { word: "photosynthesis", hint: "Process by which plants convert sunlight to energy.", difficulty: 3 },
    { word: "genotype", hint: "Genetic makeup of an organism.", difficulty: 3 },
    { word: "phenotype", hint: "Observable traits of an organism.", difficulty: 3 },
    { word: "allele", hint: "Different form of a gene.", difficulty: 3 },
    { word: "mutation", hint: "Change in DNA sequence.", difficulty: 3 },
    { word: "climate change", hint: "Long-term alteration in Earth's climate.", difficulty: 3 },
];
